[package]
name = "template-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = {version = "0.7.5"}

[dependencies.tokio]
version = "1.38.1"
features = ["full"]

[dependencies.askama]
version = "0.12.1"
features = ["with-axum"]
[dependencies.askama_axum]
version = "0.4.0"