[package]
name = "sea-orm-demo"
version = "0.1.0"
edition = "2021"
[workspace]
members = [
    ".",
    "migration"
]
[dependencies]
sea-orm = {version = "0.12.15",features = ["runtime-tokio-native-tls", "macros", "debug-print", "sqlx-mysql"]}
